### ISSUE TITLE
Upgrade to 1.7.1

### ISSUE THREAD

**Issue by lemmy** [flathub/org.lamport.tla.toolbox#25]
Toolbox 1.7.1 has been released

**Comment by jesmg** [comment]
Updated. There was some problems with the socket configuration (in Flatpak) in Fedora newer versions

**Comment by lemmy** [comment]
> Updated. There was some problems with the socket configuration (in Flatpak) in Fedora newer versions

Thanks, what kind of problems?

**Comment by jesmg** [comment]
I was always using the X11 socket, so Eclipse was not able to load. The fix (https://github.com/flathub/org.lamport.tla.toolbox/commit/9cabf3954d99124882ff4a29143daef117baeeae) was to set Wayland as main socket, and X11 as fallback.
